baseURL: "https://murphylee10.github.io/"
languageCode: en-us
title: "Murphy Lee"
theme: simple-dev-portfolio

params:
  description: "Your Description"
  preview_url: "https://murphylee10.github.io/"
